language: python

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python pet-finder.py ${API_KEY} ${SLACK_HOOK_TEST} "Australian Shepherd"
