# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:

- job: 'Run'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: python -m pip install --upgrade pip && pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: python pet-finder.py apiKey slackHook "breed"
    displayName: 'Finding Pups'      
